ALTER TABLE rz_ticket
ADD COLUMN `mobile` VARCHAR(28) DEFAULT NULL,
ADD COLUMN `fax` VARCHAR(28) DEFAULT NULL,
ADD COLUMN `postcode` VARCHAR(25) DEFAULT NULL,
ADD COLUMN `address` TEXT DEFAULT NULL,
ADD COLUMN `organization` VARCHAR(128) DEFAULT NULL,
ADD COLUMN `dept` VARCHAR(255) DEFAULT NULL,
ADD COLUMN `state_id` INT(10) DEFAULT NULL

ADD COLUMN `asset_id` INT(10) DEFAULT NULL,
ADD COLUMN `client_id` INT(10) DEFAULT NULL;