Ext.define("mhelpdesk.model.Config", {
	extend : "Ext.data.Model",
	requires : 'Ext.Date',
	config : {
		identifier : {
			type : 'uuid',
			isUnique : true
		},
		fields : [ 
		          {name : 'id', type: 'int'}, 
		          {name : 'isonline', type: 'int'}, 
		          {name : 'staff_language', type: 'string'}, 
		          {name : 'user_language', type: 'string'}, 
		          {name : 'timezone_offset', type: 'float'}, 
		          {name : 'enable_daylight_saving', type: 'int'}, 
		          {name : 'staff_ip_binding', type: 'int'}, 
		          {name : 'staff_max_logins', type: 'int'}, 
		          {name : 'staff_login_timeout', type: 'int'}, 
		          {name : 'staff_session_timeout', type: 'int'}, 
		          {name : 'user_log_required', type: 'int'}, 
		          {name : 'client_max_logins', type: 'int'}, 
		          {name : 'client_login_timeout', type: 'int'}, 
		          {name : 'client_session_timeout', type: 'int'}, 
		          {name : 'max_page_size', type: 'int'}, 
		          {name : 'max_open_tickets', type: 'int'}, 
		          {name : 'max_file_size', type: 'int'}, 
		          {name : 'autolock_minutes', type: 'int'}, 
		          {name : 'overdue_grace_period', type: 'int'}, 
		          {name : 'reopen_grace_period', type: 'int'}, 
		          {name : 'alert_email_id', type: 'int'}, 
		          {name : 'default_email_id', type: 'int'}, 
		          {name : 'default_dept_id', type: 'int'}, 
		          {name : 'default_priority_id', type: 'int'}, 
		          {name : 'default_template_id', type: 'int'}, 
		          {name : 'default_smtp_id', type: 'int'}, 
		          {name : 'spoof_default_smtp', type: 'int'}, 
		          {name : 'clickable_urls', type: 'int'}, 
		          {name : 'allow_priority_change', type: 'int'}, 
		          {name : 'use_email_priority', type: 'int'}, 
		          {name : 'enable_topic', type: 'int'}, 
		          {name : 'enable_captcha', type: 'int'}, 
		          {name : 'enable_auto_cron', type: 'int'}, 
		          {name : 'enable_mail_fetch', type: 'int'}, 
		          {name : 'enable_email_piping', type: 'int'}, 
		          {name : 'send_sql_errors', type: 'int'}, 
		          {name : 'send_mailparse_errors', type: 'int'}, 
		          {name : 'send_login_errors', type: 'int'}, 
		          {name : 'save_email_headers', type: 'int'}, 
		          {name : 'strip_quoted_reply', type: 'int'}, 
		          {name : 'log_ticket_activity', type: 'int'}, 
		          {name : 'ticket_autoresponder', type: 'int'}, 
		          {name : 'message_autoresponder', type: 'int'}, 
		          {name : 'response_notice_active', type: 'int'}, 
		          {name : 'ticket_notice_active', type: 'int'}, 
		          {name : 'ticket_alert_active', type: 'int'}, 
		          {name : 'ticket_alert_admin', type: 'int'}, 
		          {name : 'ticket_alert_dept_manager', type: 'int'}, 
		          {name : 'ticket_alert_dept_members', type: 'int'}, 
		          {name : 'message_alert_active', type: 'int'}, 
		          {name : 'message_alert_laststaff', type: 'int'}, 
		          {name : 'message_alert_assigned', type: 'int'}, 
		          {name : 'message_alert_dept_manager', type: 'int'}, 
		          {name : 'assignment_alert_active', type: 'int'}, 
		          {name : 'note_alert_active', type: 'int'}, 
		          {name : 'note_alert_laststaff', type: 'int'}, 
		          {name : 'note_alert_assigned', type: 'int'}, 
		          {name : 'note_alert_dept_manager', type: 'int'}, 
		          {name : 'overdue_alert_active', type: 'int'}, 
		          {name : 'overdue_alert_assigned', type: 'int'}, 
		          {name : 'overdue_alert_dept_manager', type: 'int'}, 
		          {name : 'overdue_alert_dept_members', type: 'int'}, 
		          {name : 'auto_assign_reopened_tickets', type: 'int'}, 
		          {name : 'hide_staff_name', type: 'int'}, 
		          {name : 'overlimit_notice_active', type: 'int'}, 
		          {name : 'email_attachments', type: 'int'}, 
		          {name : 'allow_attachments', type: 'int'}, 
		          {name : 'allow_email_attachments', type: 'int'}, 
		          {name : 'allow_online_attachments', type: 'int'}, 
		          {name : 'allow_online_attachments_onlogin', type: 'int'}, 
		          {name : 'random_ticket_ids', type: 'int'}, 
		          {name : 'log_level', type: 'int'}, 
		          {name : 'log_graceperiod', type: 'int'}, 
		          {name : 'upload_dir', type: 'string'}, 
		          {name : 'allowed_filetypes', type: 'string'}, 
		          {name : 'time_format', type: 'string'}, 
		          {name : 'date_format', type: 'string'}, 
		          {name : 'datetime_format', type: 'string'}, 
		          {name : 'daydatetime_format', type: 'string'}, 
		          {name : 'reply_separator', type: 'string'}, 
		          {name : 'helpdesk_title', type: 'string'}, 
		          {name : 'helpdesk_url', type: 'string'}, 
		          {name : 'api_passphrase', type: 'string'}, 
		          {name : 'ktsversion', type: 'string'}, 
		          {name : 'updated', type: 'date', dateFormat : 'Y-m-d H:i:s'}		          
		         ],
		proxy : {
			type : 'localstorage',
			id : 'configModel'
		}
	}
});